name: flutter_form_builder_example
description: Demonstrates how to use the flutter_form_builder plugin.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder:
    # When depending on this package from a real application you should use:
    #   flutter_form_builder: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  flutter_mobx: ^2.0.6+5
  mobx: 2.2.0
  mobx_codegen: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
