name: flutter_form_builder
description: Flutter Form Builder provides an easy way of dealing with forms and their states without creating a lot of boilerplate code.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  fake_async: ^1.3.1
  mobx: ^2.2.0
  mockito: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
