name: mobx_form_builder
description: Mobx Form Builder provides an easy way of dealing with forms and their states without creating a lot of boilerplate code.
version: 0.0.2
homepage: https://github.com/revelojobs/mobx_form_builder
repository: https://github.com/revelojobs/mobx_form_builder
issue_tracker: https://github.com/revelojobs/mobx_form_builder/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  fake_async: ^1.3.1
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
